# Generated by Django 2.2 on 2020-01-06 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_auto_20200106_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='barang',
            name='harga_barang',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
    ]
