# Generated by Django 2.2 on 2020-01-07 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0004_auto_20200107_0203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barang',
            name='pegawai',
        ),
    ]
