# Generated by Django 2.2 on 2020-01-07 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0005_remove_barang_pegawai'),
    ]

    operations = [
        migrations.AddField(
            model_name='barang',
            name='pegawai',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='barangs', to='myapi.Pegawai'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='barang',
            name='nama_barang',
            field=models.CharField(max_length=60),
        ),
    ]
